on:
  push:
    branches:
      - main
jobs:
  Code-Quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python "3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Check linting of main.py
        run: pylint main.py

  Unit-Tests:
    runs-on: ubuntu-latest
    needs:
      - Code-Quality
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python "3.12"
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run All Tests
        run: pytest

